version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
    env_file:
      - ./.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
    restart: always
